### ISSUE TITLE
Gene srf-3 not recognized in WBPaper00056075

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/afp_webapp#32]
srf-3 (WBGene00005153) appears to be mentioned 3 times:

1. in the main body of the paper
2. in the references
3. in supplementary table s4

**Comment by vanaukenk** [comment]
It also looks like the allele associated with srf-3, e2689, which is present twice, is also not recognized.

**Comment by valearna** [comment]
I only see one mention out of 3 present in the paper. One of them is srf-3-encoded, which is (correctly) ignored by the algorithm since it is not a match for the regex. The last mention is in a table, and it is not extracted by the pdf2txt conversion. I can try to improve the conversion function, but I would leave it for future work
